version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./:/usr/src/app
    command: yarn start
    ports:
      - "3001:3000"
